package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Landmark generated by hbm2java
 */
public class Landmark  implements java.io.Serializable {


     private Integer landmarkId;
     private String landAddress;
     private String landAbstract;
     private String landPicture;
     private Integer uid;
     private Date landDate;

    public Landmark() {
    }

    public Landmark(String landAddress, String landAbstract, String landPicture, Integer uid, Date landDate) {
       this.landAddress = landAddress;
       this.landAbstract = landAbstract;
       this.landPicture = landPicture;
       this.uid = uid;
       this.landDate = landDate;
    }
   
    public Integer getLandmarkId() {
        return this.landmarkId;
    }
    
    public void setLandmarkId(Integer landmarkId) {
        this.landmarkId = landmarkId;
    }
    public String getLandAddress() {
        return this.landAddress;
    }
    
    public void setLandAddress(String landAddress) {
        this.landAddress = landAddress;
    }
    public String getLandAbstract() {
        return this.landAbstract;
    }
    
    public void setLandAbstract(String landAbstract) {
        this.landAbstract = landAbstract;
    }
    public String getLandPicture() {
        return this.landPicture;
    }
    
    public void setLandPicture(String landPicture) {
        this.landPicture = landPicture;
    }
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public Date getLandDate() {
        return this.landDate;
    }
    
    public void setLandDate(Date landDate) {
        this.landDate = landDate;
    }




}


