package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Mediacontent generated by hbm2java
 */
public class Mediacontent  implements java.io.Serializable {


     private Integer mediaContentId;
     private Integer uid;
     private String headline;
     private String type;
     private String address;
     private String mediaAbstract;
     private Integer mediaId;
     private Date date;

    public Mediacontent() {
    }

    public Mediacontent(Integer uid, String headline, String type, String address, String mediaAbstract, Integer mediaId, Date date) {
       this.uid = uid;
       this.headline = headline;
       this.type = type;
       this.address = address;
       this.mediaAbstract = mediaAbstract;
       this.mediaId = mediaId;
       this.date = date;
    }
   
    public Integer getMediaContentId() {
        return this.mediaContentId;
    }
    
    public void setMediaContentId(Integer mediaContentId) {
        this.mediaContentId = mediaContentId;
    }
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getHeadline() {
        return this.headline;
    }
    
    public void setHeadline(String headline) {
        this.headline = headline;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getMediaAbstract() {
        return this.mediaAbstract;
    }
    
    public void setMediaAbstract(String mediaAbstract) {
        this.mediaAbstract = mediaAbstract;
    }
    public Integer getMediaId() {
        return this.mediaId;
    }
    
    public void setMediaId(Integer mediaId) {
        this.mediaId = mediaId;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


