package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA



/**
 * Plan generated by hbm2java
 */
public class Plan  implements java.io.Serializable {


     private Integer planId;
     private Integer authorId;
     private String planHeadline;
     private Byte planFavor;
     private String planContent;

    public Plan() {
    }

    public Plan(Integer authorId, String planHeadline, Byte planFavor, String planContent) {
       this.authorId = authorId;
       this.planHeadline = planHeadline;
       this.planFavor = planFavor;
       this.planContent = planContent;
    }
   
    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }
    public Integer getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
    public String getPlanHeadline() {
        return this.planHeadline;
    }
    
    public void setPlanHeadline(String planHeadline) {
        this.planHeadline = planHeadline;
    }
    public Byte getPlanFavor() {
        return this.planFavor;
    }
    
    public void setPlanFavor(Byte planFavor) {
        this.planFavor = planFavor;
    }
    public String getPlanContent() {
        return this.planContent;
    }
    
    public void setPlanContent(String planContent) {
        this.planContent = planContent;
    }




}


