package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Ressupplement generated by hbm2java
 */
public class Ressupplement  implements java.io.Serializable {


     private Integer resSupplementId;
     private Integer resortId;
     private String resHeadline;
     private String resContent;
     private Date resDate;
     private Integer resAuthor;
     private Integer resFrom;

    public Ressupplement() {
    }

    public Ressupplement(Integer resortId, String resHeadline, String resContent, Date resDate, Integer resAuthor, Integer resFrom) {
       this.resortId = resortId;
       this.resHeadline = resHeadline;
       this.resContent = resContent;
       this.resDate = resDate;
       this.resAuthor = resAuthor;
       this.resFrom = resFrom;
    }
   
    public Integer getResSupplementId() {
        return this.resSupplementId;
    }
    
    public void setResSupplementId(Integer resSupplementId) {
        this.resSupplementId = resSupplementId;
    }
    public Integer getResortId() {
        return this.resortId;
    }
    
    public void setResortId(Integer resortId) {
        this.resortId = resortId;
    }
    public String getResHeadline() {
        return this.resHeadline;
    }
    
    public void setResHeadline(String resHeadline) {
        this.resHeadline = resHeadline;
    }
    public String getResContent() {
        return this.resContent;
    }
    
    public void setResContent(String resContent) {
        this.resContent = resContent;
    }
    public Date getResDate() {
        return this.resDate;
    }
    
    public void setResDate(Date resDate) {
        this.resDate = resDate;
    }
    public Integer getResAuthor() {
        return this.resAuthor;
    }
    
    public void setResAuthor(Integer resAuthor) {
        this.resAuthor = resAuthor;
    }
    public Integer getResFrom() {
        return this.resFrom;
    }
    
    public void setResFrom(Integer resFrom) {
        this.resFrom = resFrom;
    }




}


