package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA



/**
 * Admininfo generated by hbm2java
 */
public class Admininfo  implements java.io.Serializable {


     private Integer adId;
     private String adPassword;
     private String adName;

    public Admininfo() {
    }

    public Admininfo(String adPassword, String adName) {
       this.adPassword = adPassword;
       this.adName = adName;
    }
   
    public Integer getAdId() {
        return this.adId;
    }
    
    public void setAdId(Integer adId) {
        this.adId = adId;
    }
    public String getAdPassword() {
        return this.adPassword;
    }
    
    public void setAdPassword(String adPassword) {
        this.adPassword = adPassword;
    }
    public String getAdName() {
        return this.adName;
    }
    
    public void setAdName(String adName) {
        this.adName = adName;
    }




}


