package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA



/**
 * Attention generated by hbm2java
 */
public class Attention  implements java.io.Serializable {


     private Integer attentionId;
     private Integer attUser;
     private Integer attedUser;

    public Attention() {
    }

    public Attention(Integer attUser, Integer attedUser) {
       this.attUser = attUser;
       this.attedUser = attedUser;
    }
   
    public Integer getAttentionId() {
        return this.attentionId;
    }
    
    public void setAttentionId(Integer attentionId) {
        this.attentionId = attentionId;
    }
    public Integer getAttUser() {
        return this.attUser;
    }
    
    public void setAttUser(Integer attUser) {
        this.attUser = attUser;
    }
    public Integer getAttedUser() {
        return this.attedUser;
    }
    
    public void setAttedUser(Integer attedUser) {
        this.attedUser = attedUser;
    }




}


