package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA



/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private Integer comId;
     private Integer uid;
     private String comContent;
     private Integer tourLogId;

    public Comment() {
    }

    public Comment(Integer uid, String comContent, Integer tourLogId) {
       this.uid = uid;
       this.comContent = comContent;
       this.tourLogId = tourLogId;
    }
   
    public Integer getComId() {
        return this.comId;
    }
    
    public void setComId(Integer comId) {
        this.comId = comId;
    }
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public String getComContent() {
        return this.comContent;
    }
    
    public void setComContent(String comContent) {
        this.comContent = comContent;
    }
    public Integer getTourLogId() {
        return this.tourLogId;
    }
    
    public void setTourLogId(Integer tourLogId) {
        this.tourLogId = tourLogId;
    }




}


