package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Good generated by hbm2java
 */
public class Good  implements java.io.Serializable {


     private Integer goodId;
     private Integer tourLogId;
     private Integer uid;
     private Date date;

    public Good() {
    }

    public Good(Integer tourLogId, Integer uid, Date date) {
       this.tourLogId = tourLogId;
       this.uid = uid;
       this.date = date;
    }
   
    public Integer getGoodId() {
        return this.goodId;
    }
    
    public void setGoodId(Integer goodId) {
        this.goodId = goodId;
    }
    public Integer getTourLogId() {
        return this.tourLogId;
    }
    
    public void setTourLogId(Integer tourLogId) {
        this.tourLogId = tourLogId;
    }
    public Integer getUid() {
        return this.uid;
    }
    
    public void setUid(Integer uid) {
        this.uid = uid;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }




}


