package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * Message generated by hbm2java
 */
public class Message  implements java.io.Serializable {


     private Integer messageId;
     private Integer authorId;
     private Integer targetId;
     private String messContent;
     private Date messDate;
     private Integer messReply;
     private Byte messRead;

    public Message() {
    }

    public Message(Integer authorId, Integer targetId, String messContent, Date messDate, Integer messReply, Byte messRead) {
       this.authorId = authorId;
       this.targetId = targetId;
       this.messContent = messContent;
       this.messDate = messDate;
       this.messReply = messReply;
       this.messRead = messRead;
    }
   
    public Integer getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(Integer messageId) {
        this.messageId = messageId;
    }
    public Integer getAuthorId() {
        return this.authorId;
    }
    
    public void setAuthorId(Integer authorId) {
        this.authorId = authorId;
    }
    public Integer getTargetId() {
        return this.targetId;
    }
    
    public void setTargetId(Integer targetId) {
        this.targetId = targetId;
    }
    public String getMessContent() {
        return this.messContent;
    }
    
    public void setMessContent(String messContent) {
        this.messContent = messContent;
    }
    public Date getMessDate() {
        return this.messDate;
    }
    
    public void setMessDate(Date messDate) {
        this.messDate = messDate;
    }
    public Integer getMessReply() {
        return this.messReply;
    }
    
    public void setMessReply(Integer messReply) {
        this.messReply = messReply;
    }
    public Byte getMessRead() {
        return this.messRead;
    }
    
    public void setMessRead(Byte messRead) {
        this.messRead = messRead;
    }




}


