package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA


/**
 * Planitem generated by hbm2java
 */
public class Planitem  implements java.io.Serializable {


     private Integer planItemId;
     private Integer planId;
     private Integer resortId;
     private String resName;
     private Integer startdate;
     private Integer enddate;

    public Planitem() {
    }

    public Planitem(Integer planId, Integer resortId, String resName, Integer startdate, Integer enddate) {
       this.planId = planId;
       this.resortId = resortId;
       this.resName = resName;
       this.startdate = startdate;
       this.enddate = enddate;
    }
   
    public Integer getPlanItemId() {
        return this.planItemId;
    }
    
    public void setPlanItemId(Integer planItemId) {
        this.planItemId = planItemId;
    }
    public Integer getPlanId() {
        return this.planId;
    }
    
    public void setPlanId(Integer planId) {
        this.planId = planId;
    }
    public Integer getResortId() {
        return this.resortId;
    }
    
    public void setResortId(Integer resortId) {
        this.resortId = resortId;
    }
    public String getResName() {
        return this.resName;
    }
    
    public void setResName(String resName) {
        this.resName = resName;
    }
    public Integer getStartdate() {
        return this.startdate;
    }
    
    public void setStartdate(Integer startdate) {
        this.startdate = startdate;
    }
    public Integer getEnddate() {
        return this.enddate;
    }
    
    public void setEnddate(Integer enddate) {
        this.enddate = enddate;
    }




}


