package tables;
// Generated Jul 7, 2013 11:43:38 AM by Hibernate Tools 3.2.1.GA



/**
 * Resort generated by hbm2java
 */
public class Resort  implements java.io.Serializable {


     private Integer resortId;
     private String resPicture;
     private String resName;
     private String resAddress;
     private String resLabel;
     private String resState;

    public Resort() {
    }

    public Resort(String resPicture, String resName, String resAddress, String resLabel, String resState) {
       this.resPicture = resPicture;
       this.resName = resName;
       this.resAddress = resAddress;
       this.resLabel = resLabel;
       this.resState = resState;
    }
   
    public Integer getResortId() {
        return this.resortId;
    }
    
    public void setResortId(Integer resortId) {
        this.resortId = resortId;
    }
    public String getResPicture() {
        return this.resPicture;
    }
    
    public void setResPicture(String resPicture) {
        this.resPicture = resPicture;
    }
    public String getResName() {
        return this.resName;
    }
    
    public void setResName(String resName) {
        this.resName = resName;
    }
    public String getResAddress() {
        return this.resAddress;
    }
    
    public void setResAddress(String resAddress) {
        this.resAddress = resAddress;
    }
    public String getResLabel() {
        return this.resLabel;
    }
    
    public void setResLabel(String resLabel) {
        this.resLabel = resLabel;
    }
    public String getResState() {
        return this.resState;
    }
    
    public void setResState(String resState) {
        this.resState = resState;
    }




}


